# Generated by Django 5.0.7 on 2024-07-26 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="birth_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="company",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="users"),
        ),
        migrations.AddField(
            model_name="user",
            name="location",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="position",
            field=models.CharField(
                blank=True,
                choices=[
                    ("business_owner", "Business Owner"),
                    ("project_manager", "Project Manager"),
                    ("product_manager", "Product Manager"),
                    ("software_engineer", "Software Engineer"),
                    ("frontend_engineer", "Frontend Engineer"),
                    ("backend_engineer", "Backend Engineer"),
                    ("qa_engineer", "QA Engineer"),
                    ("devops_engineer", "DevOps Engineer"),
                    ("ux_ui_designer", "UX/UI Designer"),
                ],
                max_length=64,
                null=True,
            ),
        ),
    ]
