version: "3.8"

services:
  db:
    image: postgres:16
    container_name: crm_backend_demo_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PORT=${DB_PORT}
    restart: always

  web:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: crm_backend_demo_web
    command: gunicorn core.wsgi:application --bind 0.0.0.0:${DJANGO_PORT} --workers=4
    volumes:
      - ./:/app
      - ./locales:/home/app/web/locales
      - ./static:/home/app/web/static
      - ./media:/home/app/web/media
    security_opt:
      - seccomp:unconfined
    env_file:
      - .env
    environment:
      - TZ=Asia/Tashkent
    ports:
      - ${DJANGO_PORT}:${DJANGO_PORT}
    depends_on:
      - db
    restart: always

volumes:
  postgres_data:
